[window]
opacity = 0.85

[font]
size = 10.0

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

[mouse]
hide_when_typing = true
